name: Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
#    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only"
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Release IKMDEV Code
        uses: ikmdev/maven-semver-release-action@v2.5.0
        with:
          ikmdevops_pat: ${{secrets.GITHUB_TOKEN}}
          github_token: ${{secrets.GITHUB_TOKEN}}
          ossrh_username: ${{secrets.OSSRH_TOKEN_USER}}
          ossrh_token: ${{secrets.OSSRH_TOKEN_PASS}}
          gpg_key: ${{secrets.GPG_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          release_version: "\\${maven.build.timestamp}"
          development_version: "\\${maven.build.timestamp}-SNAPSHOT"
          version_property: "revision"
          skip_update_version: "true"
